<?php

return [
    // --- MAIN MENU HEADER (TEMPLATE MENUS) ---
    [
        'name' => 'Main Menu',
        'type' => 'header',
        'data_lang' => 'main-menu',
        'sort_order' => 100,
    ],
    [
        'name' => 'Dashboards',
        'type' => 'item',
        'icon' => 'ti ti-layout-grid',
        'data_lang' => 'dashboards',
        'sort_order' => 101,
        'children' => [
            ['name' => 'Ecommerce', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'dashboard-ecommerce'], 'data_lang' => 'dashboard-ecommerce'],
            ['name' => 'Analytics', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'dashboard-analytics'], 'data_lang' => 'dashboard-analytics'],
            ['name' => 'Projects', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'dashboard-projects'], 'data_lang' => 'dashboard-projects'],
        ],
    ],
    [
        'name' => 'Landing',
        'type' => 'item',
        'icon' => 'ti ti-rocket',
        'route_name' => 'page',
        'route_params' => ['page' => 'landing'],
        'data_lang' => 'landing',
        'sort_order' => 102,
    ],

    // --- APPS HEADER ---
    [
        'name' => 'Apps',
        'type' => 'header',
        'data_lang' => 'apps',
        'sort_order' => 200,
    ],
    [
        'name' => 'Ecommerce',
        'type' => 'item',
        'icon' => 'ti ti-basket',
        'data_lang' => 'ecommerce',
        'sort_order' => 201,
        'children' => [
            ['name' => 'Marketplace', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-marketplace'], 'data_lang' => 'apps-ecommerce-marketplace'],
            [
                'name' => 'Products',
                'type' => 'item',
                'data_lang' => 'products',
                'children' => [
                    ['name' => 'Products', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-products'], 'data_lang' => 'apps-ecommerce-products'],
                    ['name' => 'Products Grid', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-products-grid'], 'data_lang' => 'apps-ecommerce-products-grid'],
                    ['name' => 'Product Details', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-product-details'], 'data_lang' => 'apps-ecommerce-product-details'],
                    ['name' => 'Add Product', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-product-add'], 'data_lang' => 'apps-ecommerce-product-add'],
                ],
            ],
            ['name' => 'Categories', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-categories'], 'data_lang' => 'apps-ecommerce-categories'],
            [
                'name' => 'Orders',
                'type' => 'item',
                'data_lang' => 'orders',
                'children' => [
                    ['name' => 'Orders', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-orders'], 'data_lang' => 'apps-ecommerce-orders'],
                    ['name' => 'Order Details', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-order-details'], 'data_lang' => 'apps-ecommerce-order-details'],
                    ['name' => 'Add/Edit Order', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-order-add'], 'data_lang' => 'apps-ecommerce-order-add'],
                ],
            ],
            ['name' => 'Customers', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-customers'], 'data_lang' => 'apps-ecommerce-customers'],
            ['name' => 'Cart', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-cart'], 'data_lang' => 'apps-ecommerce-cart'],
            ['name' => 'Checkout', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-checkout'], 'data_lang' => 'apps-ecommerce-checkout'],
            [
                'name' => 'Sellers',
                'type' => 'item',
                'data_lang' => 'sellers',
                'children' => [
                    ['name' => 'Sellers', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-sellers'], 'data_lang' => 'apps-ecommerce-sellers'],
                    ['name' => 'Sellers Details', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-seller-details'], 'data_lang' => 'apps-ecommerce-seller-details'],
                ],
            ],
            ['name' => 'Refunds', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-refunds'], 'data_lang' => 'apps-ecommerce-refunds'],
            ['name' => 'Reviews', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-reviews'], 'data_lang' => 'apps-ecommerce-reviews'],
            [
                'name' => 'Inventory',
                'type' => 'item',
                'data_lang' => 'inventory',
                'children' => [
                    ['name' => 'Warehouse', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-warehouse'], 'data_lang' => 'apps-ecommerce-warehouse'],
                    ['name' => 'Product Stocks', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-product-stocks'], 'data_lang' => 'apps-ecommerce-product-stocks'],
                    ['name' => 'Purchased Orders', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-purchased-orders'], 'data_lang' => 'apps-ecommerce-purchased-orders'],
                ],
            ],
            [
                'name' => 'Reports',
                'type' => 'item',
                'data_lang' => 'reports',
                'children' => [
                    ['name' => 'Product Views', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-product-views'], 'data_lang' => 'apps-ecommerce-product-views'],
                    ['name' => 'Sales Breakdown', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-sales-breakdown'], 'data_lang' => 'apps-ecommerce-sales-breakdown'],
                ],
            ],
            ['name' => 'Settings', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-ecommerce-settings'], 'data_lang' => 'apps-ecommerce-settings'],
        ],
    ],
    [
        'name' => 'Email',
        'type' => 'item',
        'icon' => 'ti ti-mail',
        'data_lang' => 'email',
        'sort_order' => 202,
        'children' => [
            ['name' => 'Inbox', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-email-inbox'], 'data_lang' => 'apps-email-inbox'],
            ['name' => 'Email Details', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-email-details'], 'data_lang' => 'apps-email-details'],
            ['name' => 'Compose', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-email-compose'], 'data_lang' => 'apps-email-compose'],
        ],
    ],
    [
        'name' => 'Users',
        'type' => 'item',
        'icon' => 'ti ti-users',
        'data_lang' => 'users',
        'sort_order' => 203,
        'children' => [
            ['name' => 'Contacts', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-users-contacts'], 'data_lang' => 'apps-users-contacts'],
            ['name' => 'Profile', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-users-profile'], 'data_lang' => 'apps-users-profile'],
        ],
    ],
    [
        'name' => 'Projects',
        'type' => 'item',
        'icon' => 'ti ti-briefcase',
        'data_lang' => 'projects',
        'sort_order' => 204,
        'children' => [
            ['name' => 'Project List', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-projects-list'], 'data_lang' => 'apps-projects-list'],
            ['name' => 'Project Details', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-projects-details'], 'data_lang' => 'apps-projects-details'],
            ['name' => 'Kanban Board', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-projects-kanban'], 'data_lang' => 'apps-projects-kanban'],
            ['name' => 'Create Project', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-projects-create'], 'data_lang' => 'apps-projects-create'],
        ],
    ],
    [
        'name' => 'File Manager',
        'type' => 'item',
        'icon' => 'ti ti-folder',
        'route_name' => 'page',
        'route_params' => ['page' => 'apps-file-manager'],
        'data_lang' => 'apps-file-manager',
        'sort_order' => 205,
    ],
    [
        'name' => 'Chat',
        'type' => 'item',
        'icon' => 'ti ti-messages',
        'route_name' => 'page',
        'route_params' => ['page' => 'apps-chat'],
        'data_lang' => 'apps-chat',
        'sort_order' => 206,
    ],
    [
        'name' => 'Calendar',
        'type' => 'item',
        'icon' => 'ti ti-calendar',
        'route_name' => 'page',
        'route_params' => ['page' => 'apps-calendar'],
        'data_lang' => 'apps-calendar',
        'sort_order' => 207,
    ],
    [
        'name' => 'Social Feed',
        'type' => 'item',
        'icon' => 'ti ti-share',
        'route_name' => 'page',
        'route_params' => ['page' => 'apps-social-feed'],
        'data_lang' => 'apps-social-feed',
        'sort_order' => 208,
    ],
    [
        'name' => 'Invoice',
        'type' => 'item',
        'icon' => 'ti ti-file-text',
        'data_lang' => 'invoice',
        'sort_order' => 209,
        'children' => [
            ['name' => 'Invoice List', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-invoice-list'], 'data_lang' => 'apps-invoice-list'],
            ['name' => 'Invoice Details', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-invoice-details'], 'data_lang' => 'apps-invoice-details'],
            ['name' => 'Create Invoice', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'apps-invoice-create'], 'data_lang' => 'apps-invoice-create'],
        ],
    ],
    [
        'name' => 'Companies',
        'type' => 'item',
        'icon' => 'ti ti-building-store',
        'route_name' => 'page',
        'route_params' => ['page' => 'apps-companies'],
        'data_lang' => 'apps-companies',
        'sort_order' => 210,
    ],

    // --- CUSTOM PAGES HEADER ---
    [
        'name' => 'Custom Pages',
        'type' => 'header',
        'data_lang' => 'custom-pages',
        'sort_order' => 400,
    ],
    [
        'name' => 'Pages',
        'type' => 'item',
        'icon' => 'ti ti-file-description',
        'data_lang' => 'pages',
        'sort_order' => 401,
        'children' => [
            ['name' => 'Starter Page', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'pages-starter'], 'data_lang' => 'pages-starter'],
            ['name' => 'Profile', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'pages-profile'], 'data_lang' => 'pages-profile'],
            ['name' => 'Pricing', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'pages-pricing'], 'data_lang' => 'pages-pricing'],
            ['name' => 'Timeline', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'pages-timeline'], 'data_lang' => 'pages-timeline'],
            ['name' => 'FAQ', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'pages-faq'], 'data_lang' => 'pages-faq'],
            ['name' => 'Maintenance', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'pages-maintenance'], 'data_lang' => 'pages-maintenance'],
            ['name' => 'Coming Soon', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'pages-coming-soon'], 'data_lang' => 'pages-coming-soon'],
        ],
    ],
    [
        'name' => 'Plugins',
        'type' => 'item',
        'icon' => 'ti ti-plug',
        'data_lang' => 'plugins',
        'sort_order' => 402,
        'children' => [
            ['name' => 'Swiper Slider', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'extended-swiper'], 'data_lang' => 'extended-swiper'],
            ['name' => 'Nestable List', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'extended-nestable'], 'data_lang' => 'extended-nestable'],
            ['name' => 'Sweet Alert', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'extended-sweetalerts'], 'data_lang' => 'extended-sweetalerts'],
            ['name' => 'Ratings', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'extended-ratings'], 'data_lang' => 'extended-ratings'],
            ['name' => 'Toastr Notifications', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'extended-toastr'], 'data_lang' => 'extended-toastr'],
        ],
    ],
    [
        'name' => 'Authentication',
        'type' => 'item',
        'icon' => 'ti ti-lock',
        'data_lang' => 'authentication',
        'sort_order' => 403,
        'children' => [
            ['name' => 'Log In', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'auth-login'], 'data_lang' => 'auth-login'],
            ['name' => 'Register', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'auth-register'], 'data_lang' => 'auth-register'],
            ['name' => 'Recover Password', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'auth-recover-password'], 'data_lang' => 'auth-recover-password'],
            ['name' => 'Lock Screen', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'auth-lock-screen'], 'data_lang' => 'auth-lock-screen'],
        ],
    ],
    [
        'name' => 'Error Pages',
        'type' => 'item',
        'icon' => 'ti ti-alert-circle',
        'data_lang' => 'error-pages',
        'sort_order' => 404,
        'children' => [
            ['name' => '404 Error', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'error-404'], 'data_lang' => 'error-404'],
            ['name' => '500 Error', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'error-500'], 'data_lang' => 'error-500'],
        ],
    ],

    // --- LAYOUTS HEADER ---
    [
        'name' => 'Layouts',
        'type' => 'header',
        'data_lang' => 'layouts',
        'sort_order' => 500,
    ],
    [
        'name' => 'Layout Options',
        'type' => 'item',
        'icon' => 'ti ti-layout-sidebar',
        'data_lang' => 'layout-options',
        'sort_order' => 501,
        'children' => [
            ['name' => 'Horizontal Layout', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'layout-horizontal'], 'data_lang' => 'layout-horizontal'],
            ['name' => 'Detached Layout', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'layout-detached'], 'data_lang' => 'layout-detached'],
            ['name' => 'Two Column Layout', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'layout-two-column'], 'data_lang' => 'layout-two-column'],
            ['name' => 'Boxed Layout', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'layout-boxed'], 'data_lang' => 'layout-boxed'],
        ],
    ],
    [
        'name' => 'Sidebars',
        'type' => 'item',
        'icon' => 'ti ti-layout-sidebar-right',
        'data_lang' => 'sidebars',
        'sort_order' => 502,
        'children' => [
            ['name' => 'Compact Sidebar', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'sidebar-compact'], 'data_lang' => 'sidebar-compact'],
            ['name' => 'Icon Only Sidebar', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'sidebar-icon-only'], 'data_lang' => 'sidebar-icon-only'],
            ['name' => 'Hidden Sidebar', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'sidebar-hidden'], 'data_lang' => 'sidebar-hidden'],
            ['name' => 'Dark Sidebar', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'sidebar-dark'], 'data_lang' => 'sidebar-dark'],
        ],
    ],
    [
        'name' => 'Topbar',
        'type' => 'item',
        'icon' => 'ti ti-layout-navbar',
        'data_lang' => 'topbar',
        'sort_order' => 503,
        'children' => [
            ['name' => 'Dark Topbar', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'topbar-dark'], 'data_lang' => 'topbar-dark'],
            ['name' => 'Gray Topbar', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'topbar-gray'], 'data_lang' => 'topbar-gray'],
        ],
    ],

    // --- COMPONENTS HEADER ---
    [
        'name' => 'Components',
        'type' => 'header',
        'data_lang' => 'components',
        'sort_order' => 600,
    ],
    [
        'name' => 'Base UI',
        'type' => 'item',
        'icon' => 'ti ti-box',
        'data_lang' => 'base-ui',
        'sort_order' => 601,
        'children' => [
            ['name' => 'Accordions', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-accordions'], 'data_lang' => 'ui-accordions'],
            ['name' => 'Alerts', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-alerts'], 'data_lang' => 'ui-alerts'],
            ['name' => 'Badges', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-badges'], 'data_lang' => 'ui-badges'],
            ['name' => 'Buttons', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-buttons'], 'data_lang' => 'ui-buttons'],
            ['name' => 'Cards', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-cards'], 'data_lang' => 'ui-cards'],
            ['name' => 'Carousels', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-carousel'], 'data_lang' => 'ui-carousel'],
            ['name' => 'Dropdowns', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-dropdowns'], 'data_lang' => 'ui-dropdowns'],
            ['name' => 'Grids', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-grid'], 'data_lang' => 'ui-grid'],
            ['name' => 'Modals', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-modals'], 'data_lang' => 'ui-modals'],
            ['name' => 'Tabs', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-tabs'], 'data_lang' => 'ui-tabs'],
            ['name' => 'Typography', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'ui-typography'], 'data_lang' => 'ui-typography'],
        ],
    ],
    [
        'name' => 'Widgets',
        'type' => 'item',
        'icon' => 'ti ti-apps',
        'route_name' => 'page',
        'route_params' => ['page' => 'widgets'],
        'data_lang' => 'widgets',
        'sort_order' => 602,
    ],
    [
        'name' => 'Metrics',
        'type' => 'item',
        'icon' => 'ti ti-chart-dots',
        'route_name' => 'page',
        'route_params' => ['page' => 'metrics'],
        'data_lang' => 'metrics',
        'sort_order' => 603,
    ],
    [
        'name' => 'Forms',
        'type' => 'item',
        'icon' => 'ti ti-forms',
        'data_lang' => 'forms',
        'sort_order' => 604,
        'children' => [
            ['name' => 'Basic Elements', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'forms-basic'], 'data_lang' => 'forms-basic'],
            ['name' => 'Form Validation', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'forms-validation'], 'data_lang' => 'forms-validation'],
            ['name' => 'Form Wizard', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'forms-wizard'], 'data_lang' => 'forms-wizard'],
        ],
    ],
    [
        'name' => 'Tables',
        'type' => 'item',
        'icon' => 'ti ti-table',
        'data_lang' => 'tables',
        'sort_order' => 605,
        'children' => [
            ['name' => 'Basic Tables', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'tables-basic'], 'data_lang' => 'tables-basic'],
            ['name' => 'DataTables', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'tables-datatables'], 'data_lang' => 'tables-datatables'],
        ],
    ],
    [
        'name' => 'Icons',
        'type' => 'item',
        'icon' => 'ti ti-icons',
        'data_lang' => 'icons',
        'sort_order' => 606,
        'children' => [
            ['name' => 'Tabler Icons', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'icons-tabler'], 'data_lang' => 'icons-tabler'],
            ['name' => 'Lucide Icons', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'icons-lucide'], 'data_lang' => 'icons-lucide'],
        ],
    ],
    [
        'name' => 'Maps',
        'type' => 'item',
        'icon' => 'ti ti-map-pin',
        'data_lang' => 'maps',
        'sort_order' => 607,
        'children' => [
            ['name' => 'Google Maps', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'maps-google'], 'data_lang' => 'maps-google'],
            ['name' => 'Vector Maps', 'type' => 'item', 'route_name' => 'page', 'route_params' => ['page' => 'maps-vector'], 'data_lang' => 'maps-vector'],
        ],
    ],
];
